### ISSUE TITLE
Getting occasional errors with uncatchable exceptions

### ISSUE THREAD

**Issue by KevBelisle** [emilianomaccaferri/query#10]
```javascript
\node_modules\minecraft-query\Query.js:31
                var players = final[1].split("\0").filter((item) => {
                                       ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Socket.<anonymous> (C:\Users\Kevin\Development\minecraft-discord-bot\node_modules\minecraft-query\Query.js:31:40)
    at Socket.emit (node:events:390:28)
    at UDP.onMessage [as onmessage] (node:dgram:939:8)
```

This is likely the same issue as #9 

I've added an additional try/catch block and extra logging around line 31, will update with more information if I get the exception again.

**Comment by KevBelisle** [comment]
It happened again.

Here's the edited section of Query.js, starting at line 28:
```javascript
                if (this.full_stat) {
                    try {
                        console.log(data.toString('utf-8', 11))
                        var final = data.toString('utf-8', 11).split("\x00\x01player_\x00\x00"); // splicing the output as suggested
                        console.log(final);
                        var kv = final[0].split("\0");
                        var players = final[1].split("\0").filter((item) => {
                            return item != "";
                        });

                        this.emitter.emit('full_stat', {
                            motd: kv[3],
                            gametype: kv[5],
                            game_id: kv[7],
                            version: kv[9],
                            plugins: kv[11],
                            map: kv[13],
                            online_players: kv[15],
                            max_players: kv[17],
                            port: kv[19],
                            players
                        });
                    } catch (err) {
                        console.log(err);
                        throw "Uh oh.";
                    }
                }
```

Here's the logs I got:
```javascript
2
[ '2\x00' ]
TypeError: Cannot read properties of undefined (reading 'split')
    at Socket.<anonymous> (C:\Users\Kevin\Development\minecraft-discord-bot\node_modules\minecraft-query\Query.js:34:48)
    at Socket.emit (node:events:390:28)
    at UDP.onMessage [as onmessage] (node:dgram:939:8)

C:\Users\Kevin\Development\minecraft-discord-bot\node_modules\minecraft-query\Query.js:52
                        throw "Uh oh.";
                        ^
Uh oh.
```

**Comment by AirplanegoBrr** [comment]
> 

Thanks for the fix!
Maybe make a pull request with ur forked fix?

**Comment by emilianomaccaferri** [comment]
sorry, i forgot about this!
thankfully @AirplanegoBrr did the job
