### ISSUE TITLE
Error: Challenge token generation timeout: client3.scrlndstore.id

### ISSUE THREAD

**Issue by ZackMans** [emilianomaccaferri/query#15]
why now, it's always like this, it wasn't like this before, please explain, and if there's a bug or something like that, please fix it

**Comment by emilianomaccaferri** [comment]
can you provide more context?

**Comment by ZackMans** [comment]
Error: Challenge token generation timeout: client3.scrlndstore.id
    at Timeout._onTimeout
(/root/ZackMans/node_modules/minecraft-query/Query.js:156:24)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by ZackMans** [comment]
i have tried it with different server but it still like that

**Comment by emilianomaccaferri** [comment]
this doesn't seem a library error. have you tried checking the server's configuration?
with what other servers have you tried?

**Comment by ZackMans** [comment]
> this doesn't seem a library error. have you tried checking the server's configuration? with what other servers have you tried?

I've tried it with many servers, but the result is still the same, and when I use "minecraft-server-util" it works fine, no problem, I like what you created, because there is an online player list on bedrock server, I've searched others no online player list on bedrock server only on java server, I really need yours, can you check it? do you work?

**Comment by emilianomaccaferri** [comment]
i didn't test this with bedrock servers, i don't really know if this is supposed to work...

anyway i'll test the library this week and i'll try to reproduce the error.
what addresses are you testing?

**Comment by ZackMans** [comment]
> 

client3.scrlndstore.id:19132
play.7togkmc.my.id:19132
play.mineluxmc.com:19132
play.kirizanetwork.xyz:19132
play.venitymc.com:19132

**Comment by emilianomaccaferri** [comment]
i'll try to see what i can do


either way, this library is very old and it's not maintained anymore (it's deprecated on npm), i recommend using something else, like minecraft-server-util, which is much more reliable

**Comment by ZackMans** [comment]
but in "minecraft-server-util" there is no online player list on bedrock server, I tried yours before and it works fine on bedrock server, online player list is also visible
