### ISSUE TITLE
[ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

### ISSUE THREAD

**Issue by XMadFoX** [emilianomaccaferri/query#4]
Hello, I have an error after 2nd request:
```
(node:33404) UnhandledPromiseRejectionWarning: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:831:11)
    at Socket.send (dgram.js:609:3)
    at ...\Query.js:85:29
(node:33404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:33404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm using Node v12.11.1 and Express 4.16.1

**Comment by emilianomaccaferri** [comment]
Did you close the connection?
That error happens when you try to query the server again after closing the connection.

**Comment by emilianomaccaferri** [comment]
By the way, thanks!
I noticed that this error wasn't rejected properly, so I fixed the problem in the [latest version](https://github.com/emilianomaccaferri/minecraft-query/commit/b67666b4a3f260a768bf55070933fa0fa5c02b29)
